### ISSUE TITLE
Rewrite interface using TTY

### ISSUE THREAD

**Issue by danielpclark** [danielpclark/language_cards#2]
Add more flexibility and use https://github.com/piotrmurach/tty 

This will allow arrow key navigation which I really want.

**Comment by danielpclark** [comment]
Looks like I'll have to postpone this since Windows support ( https://github.com/piotrmurach/tty-prompt/issues/25 , https://github.com/piotrmurach/tty-prompt/issues/31 ) has issues.  I'll reopen once a stable cross-platform solution presents itself.

**Comment by piotrmurach** [comment]
Hey just to let you know, the Windows support is now done and I will soon release new version. It would be awesome if you could give a try.

**Comment by piotrmurach** [comment]
Released `v0.11.0` that includes Windows support and quite few fixes. Please let me know how it works for you.

**Comment by danielpclark** [comment]
I'm refactoring my user interface now to make it adaptable. https://github.com/danielpclark/language_cards/tree/refactor_ui
