### ISSUE TITLE
Error deleting mkmf.log (Windows)

### ISSUE THREAD

**Issue by fabiomux** [danielpclark/language_cards#4]
checking for cls... no
c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/language_cards-0.0.4/lib/language_cards.rb:25:in `delete': Permission denied @ unlink_internal - mkmf.log (Errno::EACCES)

Commenting this line it works fine.

**Comment by danielpclark** [comment]
I'll have that disabled for Windows.  I suppose I'll need to add testing for it here.

Just curious.  Does your command line not have a `cls` command?

**Comment by danielpclark** [comment]
@fabiomux Please install gem 0.0.6 and let me know how that works for you.  Also can you tell me if the screen clears in-between each part. flash-screen to menu, to each game... does it clear the screen or just go to a new line?

**Comment by fabiomux** [comment]
Hi Daniel, well done! 
Everything works perfect now, the clear screen works also as espected: CLS > Nag screen > CLS > Game Select > CLS > Game Start.
Maybe the only missing CLS is at the very end when quitting the game...? (just wondering).
Answering to the other question... in Windows the CLS command is part of the set of instructions interpreted by CMD.exe but it doesn't exists as separate command.

**Comment by danielpclark** [comment]
Oh I see.  Well it seems the clear screen string I've used `\e[3J\e[H\e[2J` is compatible across all systems.  Thank you for your feedback!
