### ISSUE TITLE
Correct katakana and hiragana romaji

### ISSUE THREAD

**Issue by ilanusse** [danielpclark/language_cards#8]
Hey!

I really like this. I've been playing around with it and would probably like to add some basic kanji in the future.

I would, however, recommend you to look at [this chart](https://en.wikibooks.org/wiki/Japanese/Kana_chart) for the romaji that corresponds to each hiragana and their equivalent katakana since I felt a few of them were a few off.

Great work!

**Comment by danielpclark** [comment]
@ilanusse Thanks!

I took one of them (Katakana) directly from a Japanese's person's Ruby project and followed that same model for the other one with the added "Digraphs with diacritics" (personally verified with Wikipedia).  These seemingly extra characters are not included in most standard teaching documents but are documented on Wikipedia [Hiragana](https://en.wikipedia.org/wiki/Hiragana), [Katakana](https://en.wikipedia.org/wiki/Katakana).

Of course I'm not an expert on Japanese.  I'm more than willing to look into any issues here.  If you find an authority on the matter (Japanese person) with a proper mapping (ruby hash, json) in a Github repository please add a link here and I will investigate.

To my knowledge all of the standard characters are included correctly and the additional characters (Digraphs with diacritics) are mapped as I found them.

Another way to validate the characters is by turning on a keyboards mapping to the language set.  If typing the Romaji directly into the foreign characters returns a different result (and it's not Kanji) then I believe that's sufficient proof to make some changes.

---

I would love to see some basic Kanji added to this.  Perhaps Japanese Language Proficiency N1? [Japanese-Language_Proficiency_Test](https://en.wikipedia.org/wiki/Japanese-Language_Proficiency_Test)

**Comment by danielpclark** [comment]
Another option may be to separate out the special characters as another set of cards and keep the main ones purely generic.

**Comment by ilanusse** [comment]
Separating the special kana characters as another set seems like a good idea!

I think JLPT N5-N1 kanji vocab can all be included as sets of cards. I'm not sure whether it should be from kanji -> romaji (onyomi or kunyomi), kanji -> kana (onyomi or kunyomi), or maybe kanji -> english equivalent.

**Comment by danielpclark** [comment]
All of those can be acceptable collections.  Although you should flip the order for this program.

**Comment by danielpclark** [comment]
@ilanusse I have a question about the small Katakana characters.  On a keyboard they're preceeded with `x` to type them as small.  Should I try and figure out there actual short hand for them rather than the keyboard entry?

```yaml
xka: ヵ
xke: ヶ
xwa: ヮ
xtsu: ッ
xya: ャ
xyu: ュ
xyo: ョ
```

Personally I don't want the x prefix but would rather have a literal answer typed in in Romaji.  Do you also happen to know what the smaller characters are called?

**Comment by danielpclark** [comment]
I've corrected everything with the URL you gave me and the two I've posted.  I'm moved the excessive existing katakana to a Keyboard Mapping game.  This is fixed in [v0.1.2](https://github.com/danielpclark/language_cards/tree/v0.1.2)
